name: Publish NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Pack library
        run: dotnet pack FlySharp/FlySharp.csproj -c Release
      - name: Publish to NuGet.org
        run: dotnet nuget push FlySharp/artifacts/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source https://api.nuget.org/v3/index.json
